### ISSUE TITLE
Having some trouble with parseTable

### ISSUE THREAD

**Issue by troyconquer** [adrienjoly/npm-pdfreader#1]
Hi there,

Think you got a good idea here, but I'm trying to figure out how to correctly parse a table. I don't think the `displayTable()` you have in your test file is logging.. I'm just having trouble figuring out the pattern. Anyways, do you have any advice for me? 

Thanks in advance and I hope you have good day :)

Troy

```
var _ = require('lodash');
var PdfReader = require('pdfreader').PdfReader;
var Rule = require('pdfreader').Rule;

function displayTable(table){
    console.log('Object.keys(table)',Object.keys(table));
    _.map(table.rows, function(row){
        console.log('row',row);
    });
}
var sampleRules = [
    Rule.on(/^c1$/).parseTable(3).then(displayTable)
  ];
var processItemSample = Rule.makeItemProcessor(sampleRules);

var samplePathToPdf = __dirname + '/sample.pdf';
new PdfReader().parseFileItems(samplePathToPdf, function(err, item){
    if (err){
        console.log(err);
    }
    else {
        processItemSample(item);
    }
});
```

Here is my output

```
Object.keys(table) [ 'items', 'rows', 'matrix' ]
row [ { x: 20.408,
    y: 10.501,
    w: 0.9436,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: 'c2' },
  { x: 28.299,
    y: 10.501,
    w: 0.9436,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: 'c3' },
  { x: 14.979,
    y: 11.447,
    w: 0.5,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: '1' },
  { x: 29.249,
    y: 11.447,
    w: 1.25,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: '2.3' } ]
row [ { x: 19.513,
    y: 12.363,
    w: 2,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: 'hello' },
  { x: 27.068,
    y: 12.363,
    w: 2.333,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: 'world' },
  { x: 12.964,
    y: 13.248,
    w: 3.055,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: 'Values:' } ]
row [ { x: 12.964,
    y: 14.835,
    w: 0.5,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: '1' },
  { x: 12.964,
    y: 16.423,
    w: 0.5,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: '2' } ]
row [ { x: 12.964,
    y: 18.01,
    w: 0.5,
    clr: 0,
    A: 'left',
    R: [ [Object] ],
    text: '3' } ]
```

**Comment by adrienjoly** [comment]
Hi troy,

I don't understand, your output proves that it is logging, no?

Can you provide the source pdf file please?

--
Adrien Joly (mobile)
http://adrienjoly.com/

**Comment by troyconquer** [comment]
Right. I guess my real problem is I don't quite understand how to get the table to converted to JSON. Maybe it isn't exactly what the library is intended for.. So the sample.pdf table should be converted to the JSON below. Does this make sense?

```
[
	{
		"c1" : 1,
		"c2" : null,
		"c3" : 2
	},
	{
		"c1" : null,
		"c2" : "hello",
		"c3" : "world"
	}
]
```

**Comment by adrienjoly** [comment]
In order to get this kind of representation, I would iterate on the
elements (and sub-elements) of table.matrix instead of table.rows.

On Sat, Sep 12, 2015 at 7:15 PM, Troy Conquer <notifications@github.com>
wrote:

> Right. I guess my real problem is I don't quite understand how to get the
> table to converted to JSON. Maybe it isn't exactly what the library is
> intended for.. So the sample.pdf table should be converted to the JSON
> below. Does this make sense?
>
> [
>     {
>         "c1" : 1,
>         "c2" : null,
>         "c3" : 2
>     },
>     {
>         "c1" : null,
>         "c2" : "hello",
>         "c3" : "world"
>     }
> ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrienjoly/npm-pdfreader/issues/1#issuecomment-139798225>
> .
>



-- 
Adrien Joly
adrienjoly.com

**Comment by adrienjoly** [comment]
@troyconquer FYI, I just published an example of table parsing in README.md.
