### ISSUE TITLE
example not working as shown in the document

### ISSUE THREAD

**Issue by cxsphereraja** [adrienjoly/npm-pdfreader#104]
**Describe the bug**
I have tried the example that mentioned in the pdfreader npm page. it is not working. the item returns only the filename and path, but not any content available inside "item".

**To Reproduce**
<pre>
       `new pdfreader.PdfReader().parseFileItems(filename, function (err, item) {
  if (!item || item.page) {
    // end of file, or page
    console.log(renderMatrix(table.getMatrix()));
    console.log("PAGE:", item.page);
    table = new pdfreader.TableParser(); // new/clear table for next page
  } else if (item.text) {
    // accumulate text items into rows object, per line
    table.processItem(item, columnQuantitizer(item));
  }
});`
</pre>

**Expected behavior**
It should show the content

**Screenshots, outputs or logs**
If applicable, add screenshots, outputs or logs to help explain your problem.

**Desktop (please complete the following information):**
- OS: (Windows)
- Browser: (Postman Rest API )
- Version: (Node JS 16.0.0)

**Additional context**
I am executing with Node + Express JS.

**Comment by adrienjoly** [comment]
Hi, I was able to run the following script (based on the same example) successfully, from the root directory of this repository:

```
var pdfreader = require(".");

var rows = {}; // indexed by y-position

function flushRows() {
  Object.keys(rows) // => array of y-positions (type: float)
    .sort((y1, y2) => parseFloat(y1) - parseFloat(y2)) // sort float positions
    .forEach((y) => console.log((rows[y] || []).join("")));
  rows = {}; // clear rows for next page
}

new pdfreader.PdfReader().parseFileItems(
  "test/sample.pdf",
  function (err, item) {
    if (err) {
      console.error({ err });
    } else if (!item) {
      flushRows();
      console.log("END OF FILE");
    } else if (item.page) {
      flushRows(); // print the rows of the previous page
      console.log("PAGE:", item.page);
    } else if (item.text) {
      // accumulate text items into rows object, per line
      (rows[item.y] = rows[item.y] || []).push(item.text);
    }
  }
);
```

Can you share the PDF file that you are trying to parse with pdfreader?

**Comment by cxsphereraja** [comment]
Thanks. I have attached pdf files here. 
[2017101200032152784.GST-052.pdf](https://github.com/adrienjoly/npm-pdfreader/files/8368286/2017101200032152784.GST-052.pdf)
[2017101200054475959.GST-054.pdf](https://github.com/adrienjoly/npm-pdfreader/files/8368287/2017101200054475959.GST-054.pdf)

**Comment by cxsphereraja** [comment]
Hi, 

Any update on this thread. I am in production and it would be great if help us out.

**Comment by adrienjoly** [comment]
Hi! 

It looks like these PDF files do not contain textual entries. Instead they are a photograph of text.

If you want to be able to extract text from these files, you may first need to process them with a OCR software. (e.g. https://tesseract.projectnaptha.com/)

I hope this helps.

Best,

Adrien
