### ISSUE TITLE
PDF parse failed

### ISSUE THREAD

**Issue by konclave** [adrienjoly/npm-pdfreader#114]
Calling `parseFileItems` of the PdfReader instance failed with the error (in debug mode):
```javascript
import { PdfReader } from 'pdfreader';

new PdfReader({ debug: 1 }).parseFileItems("02.2022.pdf", (err, item) => {
  if (err) console.log("error:", err);
  else if (!item) console.log("end of file");
  else if (item.text) console.log(item.text);
});
```

```
Warning: Setting up fake worker.
Warning: Unhandled rejection: ReferenceError: MozBlobBuilder is not defined
ReferenceError: MozBlobBuilder is not defined
    at Object.createBlob (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:1104:12)
    at Object.createObjectURL (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:1112:24)
    at JpegStream_getIR [as getIR] (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:25575:18)
    at PartialEvaluator_buildPaintImageXObject [as buildPaintImageXObject] (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:7120:64)
    at PartialEvaluator_getOperatorList [as getOperatorList] (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:7481:20)
    at Object.eval [as onResolve] (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:4348:26)
    at Object.runHandlers (eval at <anonymous> (/Users/ivan/Sites/test/node_modules/pdf2json/lib/pdf.js:64:1), <anonymous>:864:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
``` 
[PDF for test](https://drive.google.com/file/d/1rrtKZkTe5pCVPwPeeqgtcv9L1O6s9lhw/view?usp=sharing)

- OS: MacOS 12.3
- Browser: NodeJS
- Version: 16.14.0

**Comment by adrienjoly** [comment]
Thanks for reporting. Based on https://github.com/modesty/pdf2json/issues/247, it looks like this issue would be fixed by updating the `pdf2json` dependency (used by `pdfreader`) to the latest version.

Can you try doing that in your package.json, as explained in https://github.com/adrienjoly/npm-pdfreader/issues/101#issuecomment-1001139946, and tell us if doing that solved your issue?

**Comment by adrienjoly** [comment]
Should be fixed in https://github.com/adrienjoly/npm-pdfreader/pull/116. Otherwise, feel free to re-open this issue.

**Comment by konclave** [comment]
Thank you! Unfortunately, I didn't have time to check the pdf2json version that you've mentioned. But according to the comments in pdf2json repo it should help.

**Comment by linto17** [comment]
This issue still exists

**Comment by linto17** [comment]
@adrienjoly Here is the pdf and the code : 
`return new Promise((resolve, reject) => {
        // Each item in this array represents a page in the PDF
        let pages = []
        if (!isAllPagesText(buffer)) return reject('Not a valid buffer')
        reader.parseBuffer(buffer, (err, item) => {
            if (err)
                // If we've got a problem, eject!
                reject(err)
            else if (!item)
                // If we're out of items, resolve with the data structure
                resolve(pages)
                // else if (item.page)
                // If the parser's reached a new page, it's time to
                // work on the next page object in our pages array.
                // pages.push({});
            else if (item.text) {
                    // If we have NOT got a new page item, then we need
                    // to either retrieve or create a new "row" array
                    // to represent the collection of text items at our
                    // current Y position, which will be this item's Y
                    // position.
                    // Hence, this line reads as,
                    // "Either retrieve the row array for our current page,
                    //  at our current Y position, or make a new one"
                    // const row = pages[pages.length - 1][item.y] || [];
                    // Add the item to the reference container (i.e.: the row)
                    pages.push(item.text)
                    // Include the container in the current page
                    // pages[pages.length - 1][item.y] = row;
                }
            })
            setTimeout(() => resolve(pages), 15000);
    })`
    
    
    
[03c8ec1223f47341369d88fae5e5b893.pdf](https://github.com/adrienjoly/npm-pdfreader/files/11817287/03c8ec1223f47341369d88fae5e5b893.pdf)


Code failed to execute the setTimeout function

**Comment by adrienjoly** [comment]
@linto17 I can't get this PDF file to open. Neither on my Mac or web browser. Are you sure it's a valid PDF file?

**Comment by adrienjoly** [comment]
That being said, in that case, it would be nice if pdfreader returns an error instead of freezing the Node.js process.

I'm guessing that this reveals a bug in our underlying library: pdf2json.

**Comment by linto17** [comment]
@adrienjoly This is not a valid pdf

**Comment by adrienjoly** [comment]
I'm guessing that your expectation is that, when passing an invalid buffer to PdfReader, an error should be returned.

Unfortunately, the underlying library (pdf2json) causes the freezing and does not report any error for that file. So there is nothing that PdfReader can do, unless this is fixed in pdf2json.

=> I invite you to report that error, with your file and the sample script below, to [pdf2json issues](https://github.com/modesty/pdf2json/issues):

```js
  import PDFParser from "pdf2json";
  var pdfParser = new PDFParser();
  pdfParser.on("pdfParser_dataError", console.log);
  pdfParser.on("pdfParser_dataReady", console.log);
  var verbosity = 1;
  pdfParser.loadPDF("./test-pdf.pdf", verbosity);
  setTimeout(() => console.log("does not display"), 1000);
```

**Comment by linto17** [comment]
Thanks @adrienjoly For your time and support to us!
