### ISSUE TITLE
aws lambda, sst. Error: Identifier '__dirname' has already been declared

### ISSUE THREAD

**Issue by shroomist** [adrienjoly/npm-pdfreader#140]
**Describe the bug**
module import failing with when used with sst aws lambda.
**To Reproduce**
initialize project with `npx create-sst@latest --template=base/example pdf-rest`

add handler
```ts
import { APIGatewayProxyEvent, APIGatewayProxyResult } from "aws-lambda";
import { PdfReader } from "pdfreader";
import { promisify } from "util";

export async function main(
  event: APIGatewayProxyEvent
): Promise<APIGatewayProxyResult> {
  const parser = new PdfReader(null);
  const parse = promisify(parser.parseBuffer.bind(parser));
  const a = await parse(Buffer.from(""));
  return {
    statusCode: 200,
    body: JSON.stringify(a),
  }
}
```

run `sst dev`

**Screenshots, outputs or logs**
```
|  Error: Identifier '__dirname' has already been declared
       at DefaultModuleLoader.moduleStrategy (node:internal/modules/esm/translators:116:18)
       at DefaultModuleLoader.moduleProvider (node:internal/modules/esm/loader:190:14)
       at async link (node:internal/modules/esm/module_job:67:21)
```

**Desktop (please complete the following information):**

- OS: osx darwin aarch64
- runtime: aws lambda

**Comment by adrienjoly** [comment]
There is no reference to `__dirname` in `pfdreader`, so I'm not sure how I can help...

What makes you think that the problem comes from `pdfreader` ?

**Comment by shroomist** [comment]
gotcha, digging deeper, seems like it's `pdf2json`
