### ISSUE TITLE
Import when using the library in Cypress

### ISSUE THREAD

**Issue by david-ic3** [adrienjoly/npm-pdfreader#142]
We are trying to use the library with Cypress but are getting a strange typescript error. Any help is appreciated 

**cypress.config.ts :** 
```
import {PdfReader} from "pdfreader";
... some code
```

the import gives this error : 

_TS2792: Cannot find module  pdfreader . Did you mean to set the  moduleResolution  option to  nodenext , or to add aliases to the  paths  option?_

**tsconfig.json :** 
```
{
  "compilerOptions": {
    "strict": true,
    "target": "es6",
    "lib": [
      "esnext",
      "dom"
    ],
    "types": [
      "cypress",
      "node",
      "@4tw/cypress-drag-drop",
      "cypress-real-events"
    ]
  },
  "include": [
    "**/*.ts"
  ]
}
```

**Comment by adrienjoly** [comment]
Are you sure that cypress allows importing non-cypress node packages from
their configuration files?


Le jeu. 21 sept. 2023 à 15:45, david-ic3 ***@***.***> a
écrit :
