### ISSUE TITLE
Cannot read text based PDF file content

### ISSUE THREAD

**Issue by bahadirarslan** [adrienjoly/npm-pdfreader#148]
I am trying to read a PDF file contents. It contains tabular text data and I tried the most basic example code to see how this package reads contents.

But neither is there an error nor does `item.text` has a value

```javascript
const { PdfReader } = await import("pdfreader"); // I am using CommonJS so I dynamically imported library.
    new PdfReader().parseFileItems(path.resolve(__dirname, `../../${filePath}`), (err, item) => {
//filePath was relative so I tried to resolve it, maybe this was the cause
        if (err) console.error("error:", err);
        else if (!item) console.warn("end of buffer");
        else if (item.text) console.log(item.text);
    });
```

**Comment by adrienjoly** [comment]
It's hard to help you without being able to reproduce the issue.

In order to help us do that, please share the PDF file.

**Comment by bahadirarslan** [comment]
I am sorry but I can not share the PDF file because it contains some personal info. But if you provide me an alternative way to share it with you, I can send it.

**Comment by murillocandioto** [comment]
Any update about this? I have the same problem.

**Comment by bahadirarslan** [comment]
Hello, 
Today I realized something. 
I tried my PDF file with your parser.js file and it worked. Then I copied the same code in my codes and it couldn't read.

```
if (fs.existsSync(filePath)) {
        console.log("File exists");
    }
    new pdfreader.PdfReader({ debug: true }).parseFileItems(filePath, function (err, item) {
        if (err) callback(err);
        else if (!item) callback();
        else if (item.file) console.log("file =", item.file.path);
        else if (item.page) console.log("page =", item.page);
        else if (item.x)
            console.log(
                [item.x, item.y, item.oc, item.A, Math.floor(item.w), item.text].join(
                    "\t"
                )
            );
        else console.warn(item);
    });
    return;
```
Here is the console output for this code:
`File exists`
`file = uploads/1513/imports/2024-09-08T20:08:55.599+03:00/log.PDF`

My package is up to date. The code above is copied from your example. 

`{ debug: true }` flag didn't help. How can I continue for troubleshooting?

PS: I can not send the file here publicly, but I can send to you even though I don't think it will make any difference because your example code can read it when I run `node parse.js log.PDF`

**Comment by adrienjoly** [comment]
If the pdf file and parsing code are exactly the same, the problem may come from either:
- the version of pdfreader and/or nodejs used in your project => update your package.json then delete node_modules and re-install deps;
- interference with other code and/or environment of your project => check the contents of your .env, and any other code that may be running while parsing and could have an impact on the parsing, e.g. code that runs synchronously, eats a lot of memory and/or mutates JavaScript objects.

**Comment by bahadirarslan** [comment]
While digging deeper I realized this is about `forker`. I am handling these heavy works with the forker and it seems this causes a problem while reading the file. Do you know any workarounds?

**Comment by adrienjoly** [comment]
Good job on finding the source of your problem, and thank you for having shared it with us! 🙌
