### ISSUE TITLE
isDebugMode - No such file or directory "test\data\05-versions-space.pdf"

### ISSUE THREAD

**Issue by MaelImhof** [adrienjoly/npm-pdfreader#151]
**Describe the bug**
`pdf-reader` believes it is in debug mode and tries to load the test file, which does not exist.

I fill the next fields by convention, but you're probably more interested by what I'm putting in **additional context**.

**To Reproduce**
Steps to reproduce are quite specific:

1. Setup a [Quartz](https://github.com/jackyzha0/quartz) installation
2. Create a Quartz plugin that uses `pdf-reader` as a dependency
3. Try to extract text from a PDF using `pdf-reader`

Bug can probably be encountered in other conditions, but those are mine.

**Expected behavior**
Text gets extracted, everybody's happy.

**Screenshots, outputs or logs**
*Not applicable, see in additional context for my own investigation.*

**Desktop (please complete the following information):**

- OS: Windows
- Browser: No browser used (Node.js script)
- Version: -

**Additional context**

I'm running a TypeScript script as a [Quartz](https://github.com/jackyzha0/quartz) plugin, and I want to extract text from a PDF file for it.

When I used `pdf-reader` though, it told me that the file `"test\data\05-versions-space.pdf"` did not exist, which was not the PDF I was trying to read at all.

I read the library's code and discovered `isDebugMode` in `index.js`. This was set to true for some reason. So apparently `module.parent` does not work in the case of a Node.js script? I don't know what the exact cause was, but setting `isDebugMode` to `false` manually allowed me to make everything work like a charm.

I'm gonna switch libraries because it's simpler, but I figured I could let you know about the issue anyway if that's something you want to fix.

Have a nice one !

**Comment by adrienjoly** [comment]
Thank you for your feedback.

I'm confused because I can't find any mention of `isDebugMode` nor of a `test\data\` directory in pdfreader and its dependencies. So I'm guessing that the problems that you experienced are not originating from `pdfreader` itself.

**Comment by MaelImhof** [comment]
Hi,

Very sorry about this, I somehow got `pdfreader` and [`pdf-parse`](https://gitlab.com/autokent/pdf-parse) mixed up. The problem originated from `pdf-parse`, not from your code at all.

Sorry for the trouble, have a nice one !
