### ISSUE TITLE
Error importing PdfReader

### ISSUE THREAD

**Issue by zozoyasuda** [adrienjoly/npm-pdfreader#153]
I'm using this package in a typescript project. 
```
import { PdfReader } from "pdfreader";
//...
let pdfReader = new PdfReader(); //an argument for opts is not provided - typescript error
//...
```

```
Error: require() of ES Module C:\Dev\testing\...\index.js from C:\Dev\testing\...\salesAnalysisReport.spec.ts not supported.
Instead change the require of index.js in C:\Dev\testing\...s\salesAnalysisReport.spec.ts to a dynamic import() which is available in all CommonJS modules.

   at SalesAnalysis\salesAnalysisReport.spec.ts:7

   6 | import { PdfReader } from "pdfreader";
>  7 |
     | ^
   8 | let PdfData = {};

    at Object.<anonymous> (C:\Dev\testing\...\salesAnalysisReport.spec.ts:7:18)
```
Windows 11, version 3.0.2

**Comment by Zen-cronic** [comment]
Could you provide some more context to your issue? 
For example, the test framework you're using (i'm assuming jest?), the `tsconfig` file, and a code snippet to reproduce this problem. It'd help others help you better :)

If it's `jest`, note that the framework currently doesn't support ESM modules out of the box (only experimental), so be careful when configuring the ts compilation. Currently, this library doesn't support CJS imports (only either ESM or dynamic imports). 

So, maybe your typescript tests are running after being compiled to CJS, and that's throwing an error? But without more context I can't say for sure.

**Comment by zozoyasuda** [comment]
@Zen-cronic Thank you so much for the help! This is playwright framework, I used the npm ESM package to import instead. Greatly appreciate the help even with limited information. Will keep in mind for future issue reports.
