### ISSUE TITLE
Error: Data Extraction Fails in Web Browser Using Axios/Fetch Despite Successful Backend Operation

### ISSUE THREAD

**Issue by Virgarg7** [adrienjoly/npm-pdfreader#154]
**Describe the bug**
When attempting to extract or scrape data using Axios/Fetch in a web browser, the process fails with an error. This issue persists despite the backend successfully handling and processing the data extraction.

**To Reproduce**
List the steps you followed and/or share your code to help us reproduce the bug:
1. Clone the repository and navigate to the backend folder.
2. Ensure all dependencies are installed by running `npm install`.
3. Start the backend server using `npm start`.
4. Use a web browser to make a request to the backend for extracting data from a PDF using Axios/Fetch.
5. Observe the error in the web browser console.

**Expected behavior**
The data extraction should be successful in the web browser as it is in the backend, without any errors.

**Screenshots, outputs or logs**
![image](https://github.com/adrienjoly/npm-pdfreader/assets/98869884/d8a506ca-da62-4290-935b-594299f929f6)

**Desktop (please complete the following information):**
- OS: (e.g. Windows 10, macOS 11.2)
- Browser: (e.g. Chrome, Safari)
- Version: (e.g. Chrome 91, Safari 14.1)

**Additional context**
The backend server is running fine and is able to extract data from PDFs successfully. However, when the same operation is attempted from the web browser using Axios/Fetch, it fails with a connection error.

**Comment by adrienjoly** [comment]
This issue does not seem related to pdfreader, because pdfreader does not provide HTTP endpoints.

=> Closing.
