### ISSUE TITLE
decodeURIComponent Problem

### ISSUE THREAD

**Issue by bahadirarslan** [adrienjoly/npm-pdfreader#158]
**Describe the bug**
I have a PDF file which I want to read its content unfortunately I can not make it work in my project, but it works like a charm in the example project. The code and the file are the same. 

I updated almost every package in my project, deleted the package-lock.json and node_modules folder, and re-installed the npm packages.

Here is the code that I run

```
var express = require('express');
var router = express.Router();
var pdfreader = require('pdfreader');
router.post('/', (req, res) => {
    var file = "/Users/bahadirarslan/Development/nodejs/myproject/mypdf.PDF"
    printRawItems(file, function (err) {
        if (err) {
            console.error(err);
            process.exit(1);
        }
        console.warn("done.");
    });
    res.send();
});
function printRawItems(filename, callback) {
    new pdfreader.PdfReader().parseFileItems(filename, function (err, item) {
        if (err) callback(err);
        else if (!item) callback("no file");
        else if (item.file) console.log("file =", item.file.path);
        else if (item.page) console.log("page =", item.page);
        else if (item.x) {
            console.log(
                [item.x, item.y, item.oc, item.A, Math.floor(item.w), item.text].join(
                    "\t"
                )
            );
        }
        else console.warn(item);
    });
}
module.exports = router;
```

Here is the stacktrace of the error
```
/Users/bahadirarslan/Development/nodejs/myproject/node_modules/pdfreader/dist/index.cjs:68
      item.text = decodeURIComponent(item.R[0].T);
                                           ^

TypeError: Cannot read properties of undefined (reading '0')
    at forEachItem (/Users/bahadirarslan/Development/nodejs/myproject/node_modules/pdfreader/dist/index.cjs:68:44)
    at fi.<anonymous> (/Users/bahadirarslan/Development/nodejs/myproject/node_modules/pdfreader/dist/index.cjs:94:5)
    at fi.emit (node:events:513:28)
    at #E (/Users/bahadirarslan/Development/nodejs/myproject/node_modules/pdf2json/dist/pdfparser.cjs:1:920764)
    at ci.<anonymous> (/Users/bahadirarslan/Development/nodejs/myproject/node_modules/pdf2json/dist/pdfparser.cjs:1:920931)
    at ci.emit (node:events:513:28)
    at /Users/bahadirarslan/Development/nodejs/myproject/node_modules/pdf2json/dist/pdfparser.cjs:1:916096
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.14.0
```

This PDF file contains 5 pages and the error thrown while starting a new page. Because the last thing I see in the console is the last line of the first page. 

Interestingly same printRawItems method works without any problem in the example project. So do you have a suggestion? 
This is the result for my PDF file in my project.
<img width="886" alt="Screenshot 2024-09-10 at 11 41 44" src="https://github.com/user-attachments/assets/d5fa2cbb-ddc5-4e52-b4b4-6649a44730e8">

This is the same code's result for the same file in the example project.
<img width="652" alt="Screenshot 2024-09-10 at 11 41 05" src="https://github.com/user-attachments/assets/f6887164-5a55-4f76-96f8-221567844ba2">

I created a sample express project from scratch and just pasted the code above and it worked again. Even when I copy the parse.js file from this repo to my project root and run it, it can read the same PDF file with the same code without any problem. So definitely my project caused this problem but I have no idea how can I trace it.

**Comment by bahadirarslan** [comment]
Finally, I came out with a solution.
It turned out one of our teammates added the below code one file which indirectly included almost all files that caused the problem.

```
    Array.prototype.sortBy = function () {
        return this.sort(_dynamicSortMultiple.apply(null, arguments))
    }
```

Probably your library or pdf2json does the same thing but the code above affects it so it works wrong.

If anyone has a problem like me, be suspicious about the codes like above.

**Comment by adrienjoly** [comment]
Good catch, thanks for the heads up!

**Comment by marcobaldo** [comment]
Ran into the same issue and fix worked! Thanks @bahadirarslan
