### ISSUE TITLE
Can not read pdf file

### ISSUE THREAD

**Issue by thiennhan2310** [adrienjoly/npm-pdfreader#20]
I have a file can not read. Can you take a look?
[cv_81_vietnamworks_11121.pdf](https://github.com/adrienjoly/npm-pdfreader/files/2029378/cv_81_vietnamworks_11121.pdf)

**Comment by adrienjoly** [comment]
Hi!

I'd love to help, but you could save me a lot of time by being more precise about:
- what you're doing in order to read that file? (i.e. share the code and/or commands you're using)
- what output and/or behaviour are you getting?

Can you share the details here please?

**Comment by adrienjoly** [comment]
No reply since May => closing issue.

Feel free to re-open if needed.
