### ISSUE TITLE
How can i convert the output back to PDF

### ISSUE THREAD

**Issue by pariola** [adrienjoly/npm-pdfreader#30]
Hello, i would like to make some edit to the JSON output provided by the library then convert it back to PDF, please any help would be greatly appreciated

**Comment by adrienjoly** [comment]
Hi pariola, thanks for sharing your interesting use case !
Unfortunately this package (nor pdf2json, upon which it was built) were not designed to edit or generate pdf files.
If you want to do that, you could have a look on the pdf.js package, or any other npm package that do allow to generate pdf files.
Another way would be to generate a html file from your source pdf file and then use a package that converts html to pdf.
Sorry for not being able to help you more on this, that’s where my knowledge ends on that topic... Good luck and please let us you what you ended up doing !

**Comment by pariola** [comment]
thanks for your time.

**Comment by joaodjtr** [comment]
Hello pariola, I also need to do the same. Have you found a solution to convert it back to pdf?

**Comment by pariola** [comment]
Hey @joaodjtr, I ended up using Python's PyPDF2 https://pypi.org/project/PyPDF2/

**Comment by joaodjtr** [comment]
Thanks for the response. Probably I will do the same.
