### ISSUE TITLE
having trouble parsing data that extends between pages

### ISSUE THREAD

**Issue by laneschmidt** [adrienjoly/npm-pdfreader#32]
so far, usage of this library has been really good, but I've run into an issue. basically I have a table I'm parsing data from (not using pdfreader.TableParser right now) that is split between two pages.

when I parse through each page, I use logic that finds the heading of the title to determine where it begins, and the heading of the next table to determine where it ends.

if I cannot parse across both pages, I cannot get all the data from the table.

from my understanding, I am looping through each page in my below code. I would love any suggestions as I've sort of hit a roadblock here.

please note that I'm using the Serverless framework and invoking it that way; sorry if it's very unrepeatable for anybody.

**code**:

```
function getNextIndexItem(rows, num, currentItem) {
  /*
  get the item that appears next in the array passed into the rows param.
  param rows: array of rows parsed on the page
  param num: number of indexes past the current index (currentItem)
  param currentItem: the index of the current item in the array
  */ 
  let keys = Object.keys(rows);
  let nextIndex = keys.indexOf(currentItem) + num;
  let nextItem = keys[nextIndex];
  let nextField = (rows[nextItem] || []).join(' ');
  let finalStr = nextField.split(':')[nextField.split(':').length-1];

  return finalStr;
}

function pdfReader(pdfFilePath, parsedData, callback) {
  const pdfreader = require("pdfreader");

  let rows = {}; // indexed by y-position
  let tableIndexes = 0;

  new pdfreader.PdfReader().parseFileItems(pdfFilePath, (err, item) => {
    if (err) callback(err);

    if (item) {
      if (item.page) {
        // end of file, or page
        Object.keys(rows) // => array of y-positions (type: float)
          .sort((y1, y2) => parseFloat(y1) - parseFloat(y2)) // sort float positions
          .forEach(yValue => {
            // rows[y] is an array of text for a line.
            let line = (rows[yValue] || []).join('');  // construct line of text

            if (line.includes('Table Name')) {
              tableIndexes = 0;
              for (let i = 0; i < 500; i++) {
                if (getNextIndexItem(rows, i, yValue).includes('Next Table Name')) {
                  tableIndexes = i;  // get index of last table row
                  break;
                }
            }
            for (let i =2; i < tableIndexes; i++) {  // start at 2 to avoid the heading row of the table
              console.log(`List row #${i}: ${getNextIndexItem(rows, i, yValue)}`);
            }
          });
        rows = {}; // clear rows for next page
      } else if (item.text) {
        if (!rows[item.y]) {
          rows[item.y] = [];
        }
        rows[item.y].push(item.text);
      }
    } else {
      // we're done here
      callback(parsedData);
    }
  });
};

module.exports.test = function() {
  pdfReader('doc.pdf', (err, data) => {
    if (err) console.log(err);
  });
}
```

here's the table in the PDF:
<img width="642" alt="Capture" src="https://user-images.githubusercontent.com/38232529/59374960-53679f00-8d0a-11e9-9945-ad8dc8861bbc.PNG">

**Comment by adrienjoly** [comment]
Hi Lane, thanks for having taken the time to report your problem here!

Unfortunately, I won’t have the time to take a proper look at it before the next weekend...

The only tip I may give is: if I wanted to accumulate data across several pages, I would read the entire file with pdf reader, store all the text items I found into an array and ignore the « page » items. Only then I would filter (if necessary) the array of text items and try to reconstruct the table structure based on their coordinates.

In the mean time, I hope that you will find a solution and share it here, or get help from another user.

Best regards !

Adrien

**Comment by adrienjoly** [comment]
Hey Lane!

It's hard to witness the problem without being able to reproduce.

=> can share a PDF file that we could run your script on?

**Comment by adrienjoly** [comment]
No news = closing.
