### ISSUE TITLE
embarassingly slow

### ISSUE THREAD

**Issue by Amadeus82** [adrienjoly/npm-pdfreader#41]
**Describe the bug**
Parsing a pdf file containing 235 pages takes up to 8 seconds (just doing nothing with the received tokens - apparently the lexer alone takes up that much time) :-p

**To Reproduce**
```
const parseStart = process.hrtime();
new PdfReader().parseBuffer(result.data, (err, item) => {
                        // the pdf reader signals the end of the parsing process
                        // by calling this function with the item set as undefined
                        if (!item) {
                            const parseEnd = process.hrtime(parseStart);
                            this.logger.log(`parse pdf completed in ${parseEnd[0]}.${Math.floor(parseEnd[1] / 10e6)}s`);

                            observer.next(table);
                            observer.complete();
                            return
                        }
});
```

**Expected behavior**
I would expect to have a pdf file of this size to have no longer than 2 seconds to parse.

**Screenshots, outputs or logs**
parse pdf completed in 7.42s SkybriefingDaylightAdapter

**Desktop (please complete the following information):**

- OS: Windows 10, but it doesn't matter, its the same on a linux virtual machine.

**Additional context**
I have attached a sample file.
[pdf.pdf](https://github.com/adrienjoly/npm-pdfreader/files/4003273/pdf.pdf)

**Comment by adrienjoly** [comment]
Thanks for having shared this benchmark results, Samuel!

It would be interesting to know what part of the system takes the most time, while parsing a pdf. It may come from:
- this package
- the `pdf2json` dependency
- or `pdf.js`, the pdf parsing engine which is wrapped by `pdf2json`

I believe that there are several ways to achieve that:
- run the same test in audit mode, e.g. with [node-clinic](https://github.com/nearform/node-clinic)
- or implement and run the same test directly against each dependency, i.e. against pdf2json, then against pdf.js directly.

If you decide to do it, I'd be interested in knowing the results. Let me know if I can assist in any way.

**Comment by adrienjoly** [comment]
No news => closing.
