### ISSUE TITLE
How to know when pdfreader finished reading a file?

### ISSUE THREAD

**Issue by edutucci** [adrienjoly/npm-pdfreader#42]
I am not able to find out when a file finished your reading. I need call a function when a file finished your reading.

**Comment by adrienjoly** [comment]
Hi Eduardo,
As mentioned in the README of the project on GitHub, the callback function you pass to PdfReader.parseFileItems() or PdfReader.parseBuffer() will be called with ˋnull` when the parsing is over, or if an error occured.
I am in vacation for a few days, so I hope that this answer and/or the README will help you use pdfreader. If that’s not the case, please provide your code below so we can try to help you from there.
Also, don’t hesitate to propose a pull request to help us improve our README documentation.
Best regards,
Adrien

**Comment by edutucci** [comment]
I found a way to call a function when parse file is over.
Thanks. I will add the code in git hub to help others users.

Em sex, 21 de fev de 2020 14:57, Adrien Joly <notifications@github.com>
escreveu:

**Comment by edutucci** [comment]
Here is my example. Sorry, I did not send before.

var table = null;
var pdfPages = [];
 
new pdfreader.PdfReader().parseFileItems(filename, function(err, item) {
  if (item && item.page) {
    // end of file, or page
    // if(table) console.log(renderMatrix(table.getMatrix()));
    if(table) {
      // console.log(JSON.stringify(table.getMatrix()));
      pdfPages.push(table.getMatrix());
    } 
    // console.log("PAGE:", item.page);
    table = new pdfreader.TableParser(); // new/clear table for next page
  } else if (item && item.text) {
    // accumulate text items into rows object, per line
    // console.log(item);
    table.processItem(item, 0); // columnQuantitizer(item));
  } else {
    // fim
    if (!item) {
      console.log('end of file')
      if(table) {
        // console.log(JSON.stringify(table.getMatrix()));
        pdfPages.push(table.getMatrix());
      }

      pdfPages.forEach(page => {
        console.log(JSON.stringify(page))
      });
    }
  }
});
