### ISSUE TITLE
How to get raw text 

### ISSUE THREAD

**Issue by mundane140** [adrienjoly/npm-pdfreader#55]
I am trying to parse a pdf and catagorize information based on text formatting/decoration. How do you suggest I do that?
For example, I have a pdf in which the structure is repeated:
S.No. BOLD+UNDERLINED TITLE para 

How do I catagorize this data into an array of objects:
`
[
  {
     sno: "",
     title: "",
     desc: ""
  },
  ...
]
`

**Comment by mundane140** [comment]
I went through the documentation for [pdf2json](https://github.com/modesty/pdf2json#page-object-reference) and figured that I might have to use `pdfData.formImage.Pages[pageNumber].Texts[wordNumber].R[0]` object after parsing the pdf to get hold of values I need.
The property `TS` of the above object is an array, the value at `TS[2]` corresponds to whether the text is bold (value = 1) or not (value = 0). 

I also needed to initialize the parser as follows:
`let pdfParser = new PDFParser(null, 1)`

**Comment by adrienjoly** [comment]
Thanks for sharing the result of your investigation, Akshay! 👌
