### ISSUE TITLE
I have to try catch this place, if not, sometimes, will throw error "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by caihaibin1991** [adrienjoly/npm-pdfreader#58]
![image](https://user-images.githubusercontent.com/5326638/92218510-d22a9800-eecb-11ea-9a61-d47b841fee2a.png)

**Comment by adrienjoly** [comment]
Thanks for reporting this issue! Can you share a PDF document that causes this error, so we can reproduce it, please?

**Comment by caihaibin1991** [comment]
It is not a pdf problem, When I start a server and run the parse code, It will throw this problem, but when I directly run this code, It is normal... It is so strange...
this is the screenshot.
![image](https://user-images.githubusercontent.com/5326638/92220395-86c5b900-eece-11ea-9549-7f9445ea4c79.png)
Might be I know why now.

**Comment by adrienjoly** [comment]
What do you mean by "start a server". What server are you referring to?
