### ISSUE TITLE
Missing text height

### ISSUE THREAD

**Issue by dariusstephen** [adrienjoly/npm-pdfreader#72]
Hello, I am using the code snippet from the documentation to parse lines of text from pdf page.
The lines of text are getting parsed, however for some reason the height / h property is missing from item.
I need the height in order to detect the text getting out of bound of a certain box on the pdf page.

Here is the code snippet, that I used:
`
  let rows = {};
  let addressRows = [];

    const printRows = () => {
      Object.keys(rows)
        .sort((y1, y2) => parseFloat(y1) - parseFloat(y2))
        .forEach((y) => {
          addressRows.push((rows[y] || []).join(''));
        });
    }
 
    new pdfreader.PdfReader().parseFileItems(tempPath, function (err, item) {
      if (!item || item.page) {
        printRows();
        if (!item) {
          console.log('addressRows: ', addressRows)
        }
      } else if (item.text) {
        console.log(item);

        // accumulate text items into rows object, per line
        (rows[item.y] = rows[item.y] || []).push(item.text);
      }
 });`

Here is the log I received on terminal.

![Screen Shot 2020-12-12 at 5 34 23 PM](https://user-images.githubusercontent.com/4991360/101981554-51382500-3ca0-11eb-90f6-aa87c06c9221.png)

Any idea why the height/h property is missing?
Thank you.

**Comment by adrienjoly** [comment]
Hi Darius!

As you can see in the source code (https://github.com/adrienjoly/npm-pdfreader/blob/master/PdfReader.js#L52), pdfreader passes the text entries as-is, from [pdf2json/pdfparser](https://github.com/modesty/pdf2json).

So my recommendation would be that you check if pdfparser's latest version can provided the height of text entries, or ask them directly for advice/support otherwise.

Best regards.

Adrien

**Comment by dariusstephen** [comment]
Hi Adrien,

Thanks for the quick response and help!
I have taken a look at [pdf2json/parser](https://github.com/modesty/pdf2json#page-object-reference) documentation and it looks like there is no height for the text field after all.

I found this [answer](https://stackoverflow.com/questions/44674668/pdf-how-to-get-height-of-text) on stackoverflow to get the height of the text from font size, which I will look into and in case anyone else is also looking for this.

I think the pdfreader docs can to be updated as there is no `h:float` inside Text items.

Best,
Darius

**Comment by adrienjoly** [comment]
Thanks for the feedback!

Don't hesitate to propose an update of the documentation by creating a Pull Request, if you feel like it. ^^

Adrien
