### ISSUE TITLE
pdf2json has vulnerabilities, patched in >=0.5.0. Please update this library to resolve the issue.

### ISSUE THREAD

**Issue by developerfromjokela** [adrienjoly/npm-pdfreader#80]
NPM is showing me 4 vulnerabilities, (3 low, 1 high) for pdf2json. Patched after 0.5.0. I recommend updating dependencies list.

**Comment by adrienjoly** [comment]
Thank you for the suggestion!
Until I find the time to proceed, feel free to create a Pull Request for this.
