### ISSUE TITLE
locate absolute position of item

### ISSUE THREAD

**Issue by jos1337** [adrienjoly/npm-pdfreader#9]
Im trying to find a string in a string in a pdf and want to get its x and y location on a page.
It seems item.x and item.y are relative to the item "above". it seems impossible to me to find out which x to add to get the absolute position of an item.
is there any way?

**Comment by adrienjoly** [comment]
Hi, @jos1337 !

I believe that `item.x` and `item.y` are absolute coordinates.

If you want more help, please provide the PDF, and the steps+code I can follow & run, to investigate.

**Comment by jos1337** [comment]
thank you. it seems that item.x and item.y are not in a global document context. I have been able to solve this with hummus.js so i didn't investigate further.

**Comment by adrienjoly** [comment]
They are indeed not relative to the whole PDF document, but rather to the page they belong too.

I didn't know about hummus.js, I'll check it out. Thanks for mentioning it!
