### ISSUE TITLE
Does not work in node v16.10.0

### ISSUE THREAD

**Issue by samuel-papinotas** [adrienjoly/npm-pdfreader#91]
**Describe the bug**
When running with `node v16.10.0`, the methods `parseBuffer` and `parseFileItems` do not work as expected.

**To Reproduce**
Use node version 16.10.0 and try to read the text of a pdf using `parseBuffer` or `parseFileItems`

**Expected behavior**
The callback passed to `parseBuffer` or `parseFileItems` should be called with each pdf item found.

**Current behavior**
The callback passed to `parseBuffer` or `parseFileItems` only gets called once with the `file: { path }` or `file: { buffer }` data, and never gets called with the pdf items or pages.

**Screenshots, outputs or logs**

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.4
- Browser: node.js
- Version: 16.10.0

**Aditional Info**

The same code works correctly in at least node 16.3.0

**Comment by adrienjoly** [comment]
Thank you for taking to the time to submit this very clear issue, Samuel!

Feel free – yourself or anyone else who feels like it – to propose a fix as a pull request.

**Comment by k2s** [comment]
Possible fix for this issue is in #97.

**Comment by Niraj27jha** [comment]
> self or anyone else who feels like it –

in node version v16.13.1 it is not reading text
