### ISSUE TITLE
pdf2json dependency is broken

### ISSUE THREAD

**Issue by Turtleb01** [adrienjoly/npm-pdfreader#95]
pdf2json update from 1.2.5 to 1.3.0 removed formImage, which pdfreader requires, without incrementing the major version number as they should with incompatible changes. NPM thinks that 1.2.5 and 1.3.* are compatible. As a temporary patch, you could set the dependency in package.json to something like <=1.2.5

**Comment by adrienjoly** [comment]
Thanks for the heads up!

Automated tests should have failed, if pdfreader does not work after that update… Any idea why they didn’t? 🤔

**Comment by Turtleb01** [comment]
This is really weird. If I git clone this repo and run `npm i`, it will install pdf2json 1.2.5, but if I start with an empty directory and run `npm i pdfreader`, it will install 1.3.1.

**Comment by Turtleb01** [comment]
I think I figured it out: it's package-lock.json. It sets pdf2json version to 1.2.5, but package-lock.json isn't shipped with the npm package. I'm not familiar with npm module best practices, but I don't think there should be any discrepancies between it and this repository.

**Comment by adrienjoly** [comment]
Good catch!

Unfortunately, I found out that `npm` does not publish `package-lock.json`, as stated on [npm docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson):

> `package-lock.json` cannot be published, and it will be ignored if found in any place other than the root project.

That said, if `pdf2json` refuse to create a major version (which would be the right thing to do, considering that their recent change is a breaking one), this could be a workaround worth trying:

> In contrast, `npm-shrinkwrap.json` allows publication, and defines the dependency tree from the point encountered.

Feel free to give it a try and propose a Pull Request if this solution solves your problem!

Adrien

**Comment by adrienjoly** [comment]
I just fixed the version of `pdf2json` to `1.2.5` (instead of `^1.2.5`), as an attempt to prevent it from being upgraded when installing `pdfreader` as a dependency of a Node.js project: https://github.com/adrienjoly/npm-pdfreader/commit/bbf2e228363eec4999f9f948b6774360e22f840c

Does this fix your problem, by any chance?

**Comment by mxs17** [comment]
Hi Adrien!

I have bumped into a new problem with `pdf2json` of nearest versions. I have a set of PDFs that were successfully imported earlier, I believe, around `pdfreader's` version `1.2.8`. Now, I am trying to import them again, and for some files process of import ends silently in 3-4 seconds with no errors and no callbacks invocation. I tried all the versions one by one - no luck.

I have just checked `pdf2json` repo, and I see a new major version `2.0.0` released 3 days ago. It somehow parses these files again. :) 

Is it possible to release some minor update of `pdf2reader` with `pdf2json` `2.0.0`?

**Comment by adrienjoly** [comment]
FYI, @k2s proposed a fix that may make pdfreader compatible with pdf2json 2.0: https://github.com/adrienjoly/npm-pdfreader/releases/tag/v1.2.14

Check it out and please let us know if it works, when it's available on npm.

**Comment by mxs17** [comment]
I have installed `1.2.14` from npm, and I see `pdf2json` `1.2.5` in package-lock.json. So, it still silently does nothing with my test file. Is there a way to specify the version of `pdf2json` on my side?

**Comment by adrienjoly** [comment]
Have you tried specifying a different version of pdf2json in the "resolutions" section of package.json yet, as proposed there: https://github.com/adrienjoly/npm-pdfreader/pull/97 ?

**Comment by mxs17** [comment]
Thanks! I missed the initial point about the "resolutions". I have tried it, and I see it works as expected when the dependencies are installed with `yarn`, but I cannot find a workaround for `npm` v.8 (I tried `npm-force-resolutions` in `preinstall`, but could not make it working).
